language: python

env:
  - TOX_ENV=py26
  - TOX_ENV=py27
  - TOX_ENV=py26-simplejson
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=docs

install:
  - pip install tox coveralls

script:
  - tox -e $TOX_ENV

after_success:
  - tox -e cover
  - coveralls

sudo: false
